// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6U_ohECHTlfnPvnoOqIyQnLtF97A8Ynw',
    appId: '1:540450109795:web:d20abfee6a10804abefb56',
    messagingSenderId: '540450109795',
    projectId: 'shinappro-aadb2',
    authDomain: 'shinappro-aadb2.firebaseapp.com',
    storageBucket: 'shinappro-aadb2.appspot.com',
    measurementId: 'G-5FT191Y1J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0PO8P2du80hp6hNKnIHxWdgcw-JeCDCM',
    appId: '1:540450109795:android:68e87039dc0053edbefb56',
    messagingSenderId: '540450109795',
    projectId: 'shinappro-aadb2',
    storageBucket: 'shinappro-aadb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKlNNhbv3gFz9YZmA3Id-3UHMi8pZ9pZQ',
    appId: '1:540450109795:ios:2e09d7c5e556a6bfbefb56',
    messagingSenderId: '540450109795',
    projectId: 'shinappro-aadb2',
    storageBucket: 'shinappro-aadb2.appspot.com',
    androidClientId: '540450109795-0cjpntful3v4onogq2nnv3rj46glfleh.apps.googleusercontent.com',
    iosClientId: '540450109795-ch9r5a84hjec1t12cdltvritube3rl9f.apps.googleusercontent.com',
    iosBundleId: 'edu.handong.ASARR.shinappro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKlNNhbv3gFz9YZmA3Id-3UHMi8pZ9pZQ',
    appId: '1:540450109795:ios:69c19099c72d1a31befb56',
    messagingSenderId: '540450109795',
    projectId: 'shinappro-aadb2',
    storageBucket: 'shinappro-aadb2.appspot.com',
    androidClientId: '540450109795-0cjpntful3v4onogq2nnv3rj46glfleh.apps.googleusercontent.com',
    iosClientId: '540450109795-0oeb48i838p3th4g34ji366g9sgab6p3.apps.googleusercontent.com',
    iosBundleId: 'edu.handong.ASARR.shinappro.RunnerTests',
  );
}
